#!/usr/bin/env python
from std_srvs.srv import Empty, EmptyResponse 
import rospy
import sys



if __name__ == "__main__":
    rospy.init_node("callservice")
    rospy.wait_for_service('clearpointservice')
    print("Calling Service")
    try:
        checkpoint = rospy.ServiceProxy('clearpointservice', Empty)
        checkpoint()
    except rospy.ServiceException as e:
        print ("Service call failed: %s" % e)
    
