#!/usr/bin/env python
import sys
import rospy
from tf.transformations import euler_from_quaternion
from crazyflie_driver.msg import Position
from geometry_msgs.msg import TransformStamped, Vector3, PoseStamped
import numpy as np
from std_srvs.srv import Empty, EmptyResponse 


def current_position(msg):
    global yaw
    quat = msg.pose.orientation
    _, _, yaw = euler_from_quaternion([quat.x, quat.y, quat.z, quat.w])

    yaw = round((180./np.pi)*yaw)


def spin_360():

    rotation=0

    while rotation <360:
        cmd.yaw=yaw+rotaterate
        pos_publish.publish(cmd)
        rotation+=rotaterate
        rate.sleep()

    return EmptyResponse

cmd=Position()
rotaterate=45
rate = rospy.Rate(5)


current_pose=rospy.Subscriber("cf1/pose", PoseStamped, current_position)
pos_publish=rospy.Publisher("/cf1/cmd_position", Position,queue_size=10)

if __name__=="__main__":
    rospy.init_node('clear_checkpoint_node')
    s = rospy.Service('clearpointservice', Empty, spin_360)

    

