#!/usr/bin/env python

import math
import rospy
import tf2_ros
import tf2_geometry_msgs
from tf.transformations import euler_from_quaternion
from geometry_msgs.msg import PoseStamped
from crazyflie_driver.msg import Position, Hover
import random
import readchar


# def hight(msg):
#     global h
#     h = msg.pose.position.z

def send_keys():
  

    cmd = Position()
    key = readchar.readkey()

    #cmd.vx = 0
    #cmd.vy = 0
    #cmd.zDistance = h
    #cmd.yawrate = 0


    if key=='w':
        cmd.x=0.25

    if key=='s':
        cmd.x=-0.25
    
    if key=='a':
        cmd.y=0.25

    if key=='d':
        cmd.y=-0.25

    if key=='u':
        cmd.z= 0.4
    
    if key=='j':
        cmd.z=-  0.4  
        
    if key=='x':
        cmd.yaw=22.5
    
    if key=='z':
        cmd.yaw=-22.5
    
    
    if key=='r':
        cmd.z=0.4
        cmd.x=0
        cmd.y=0
        cmd.yaw=0


    
    

    if key=="e":
        return True

    fly_crazyflie.publish(cmd)



#count = 0
#sub = rospy.Subscriber("cf1/pose", PoseStamped, hight)
fly_crazyflie=rospy.Publisher("goal", Position ,queue_size=10)





if __name__ == '__main__':

    rospy.init_node('touchkeys')
    
    
    
    
    rate = rospy.Rate(10)
    while not rospy.is_shutdown():
        c= send_keys()
        rate.sleep()
        if c:
            break


    # rospy.spin()
    